### ISSUE TITLE
feature request - add ability to specify project

### ISSUE THREAD

**Issue by DanTaranis** [Advestis/transparentpath#62]
I'm getting : 
```
  File "/usr/local/lib/python3.6/dist-packages/transparentpath/gcsutils/transparentpath.py", line 625, in set_global_fs
    raise ValueError("Need to provide a project name!")
```
I don't see a way to let transparent path know which project I'd like to use other than using a token

**Comment by pcotteadvestis** [comment]
Hi ! Thank you for opening and issue here. You're the first to do so outside of my direct collaborators  ! I'll look into it right away.

**Comment by DanTaranis** [comment]
I'll take this opportunity to say thank you! this library is super awesome

**Comment by pcotteadvestis** [comment]
Which version are you using ? What does `pip show transparentpath` says ? Most likely your version is outdated, please run `pip install -U transparentpath`. In the latest versions, *project* is automatically found from your local GCP configuration if you ran `gcloud init` already or if you execute *set_global_fs* on GCP directly (in a VM for instance). If you have the *GOOGLE_APPLICATION_CREDENTIALS* environment variable set, that should do it too.

If updating transperentpath does not give you the version **0.3.262** (or greater for those who will read this message after today), then most likely your are in a virtualenv that forces some other packages versions below that of what transparentpath **0.3.262** requires, making pip fetch an older version.

For your information, the only packages that are explicitly fixed are 
  * gcsfs==2021.10.0
  * fsspec==2021.10.0

Check that your venv allows those version.

**Comment by DanTaranis** [comment]
I created a docker this morning with the latest version - I'm not sure what the version is

**Comment by DanTaranis** [comment]
it looks like I don't have GOOGLE_APPLICATION_CREDENTIALS for some weird reason

**Comment by pcotteadvestis** [comment]
Ok, if it is with docker it might be my fault, I have not checked it in a while. I'll do that, but in the mean time you can always use a basic python docker image and do `pip install transparentpath` in it, something like.

`
FROM python:3.9-slim

RUN pip install -U pip && pip install transparentpath
...
`

**Comment by DanTaranis** [comment]
I'm rechecking - it should have it. I'll let you know in a minute.

**Comment by DanTaranis** [comment]
my apologies - the docker does have GOOGLE_APPLICATION_CREDENTIALS as an environment variable. more over if I use fs = gcsfs.GCSFileSystem(project='my-google-project') with my project id I am able to create an fs

**Comment by pcotteadvestis** [comment]
I just found that the docker does not use the latest version. I'll fix that right away and let you know when it's ok.

**Comment by pcotteadvestis** [comment]
Aaaah ok, then you should get the latest version. If you run your docker with bash and do `pip show transparentpath`, what does it say ?

**Comment by DanTaranis** [comment]
Name: transparentpath

Version: 0.1.129

Summary: A class that allows one to use a path in a local file system or a gcs file system (more or less) in almost the same way one would use a pathlib.Path object.

Home-page: https://github.com/Advestis/transparentpath

Author: Philippe COTTE

Author-email: pcotte@advestis.com

License: UNKNOWN

Location: /usr/local/lib/python3.6/dist-packages

Requires: pathlib, dask, datetime, h5py, bokeh, pyarrow, gcsfs, xlrd, fsspec, tables, pytest, google-auth, pandas, openpyxl, numpy, setuptools

**Comment by DanTaranis** [comment]
interesting -  why is it not downloading the latest - I'll try to force it to update

**Comment by pcotteadvestis** [comment]
Yeah, definitely outdated, of several months. And I do not know why it does not get the latest either. Can you pass your entire dockerfile here ? Or send it by mail at pythondev@advestis.com.

**Comment by DanTaranis** [comment]
I tried to explicitly tell it to upgrade :
```

Step 6/9 : RUN pip install transparentpath -U

 ---> Running in 7185e225c71c

Looking in indexes: https://pypi.org/simple, https://1E0iDm-C99SbhHfu8wHm2GTWDLK4RL4c:****@pypi.fury.io/TARANIS/

Requirement already up-to-date: transparentpath in /usr/local/lib/python3.6/dist-packages (0.1.129)
```

**Comment by DanTaranis** [comment]
maybe it's the python3.6?

**Comment by pcotteadvestis** [comment]
Aaaaaah yes support for python 3.6 ended a while ago. Can you use 3.7 or later ?

**Comment by DanTaranis** [comment]
ok. perfect. thanks for helping me find the issue.
