### ISSUE TITLE
conflict with fsspec version required by gcsfs

### ISSUE THREAD

**Issue by mwintner-fn** [Advestis/transparentpath#76]
Hello! There is a conflict between the versions of `fsspec` required by the most recent `gcsfs` and `transparentpath`. In particular, `gcsfs==2022.2.0` depends on `fsspec==2022.02.0` and `transparentpath` depends on `fsspec==2021.10.0`. Hopefully this is a quick fix. Thanks for this project, by the way, it's super helpful!

**Comment by pcotteadvestis** [comment]
Hello ! Thanks for bringing this to my attention, I'll look into it right away.

**Comment by pcotteadvestis** [comment]
The current version of transparentpath (1.0.26 as of now) specifically needs **gcsfs==2021.10.0**, so if you are using it with **gcsfs==2022.2.0**, it is normal that you encounter difficulties. i nonetheless opened a PR specifying the most recent versions of **gcsfs** and **fsspec**, the pytests will tell if the code is compatible with them :)
