### ISSUE TITLE
Is there a way to build absolute paths from TransparentPath objects?

### ISSUE THREAD

**Issue by aginpatrick** [Advestis/transparentpath#80]
I'm trying to build complete path filenames from TransparentPath objects as functions I'm trying to use are expecting path strings. 

Ideally I would call a method like path.absolute to get "/my/absolute/path/filename" if local or "gs://my-bucket/filename" if GCS.

For the moment I've coded this functionality as :

```
base_dir = Path("/images/tfrecords")
TRAIN_FILENAMES = base_dir.glob("train*.*")
prefix = "gs://" if FS == 'gcs' else ''
TRAIN_FILENAMES = [prefix + base_dir.path.as_posix() + "/" + el.name for el in TRAIN_FILENAMES]
```

Maybe there is a way to do it already that I don't know?
Thanks for your repo!

**Comment by pcotteadvestis** [comment]
All TPs are absolute by default. You can just cast them in str and it should do the trick.
If this solved your problem, I'll let you close the issue.
From what I gather from your example, you should try to use "set_global_fs" by specifying the bucket name and let TP do its job. Look at the example in the Readme of TP github repo

**Comment by aginpatrick** [comment]
Thanks for your answer. It's working with the string cast. I'll close the issue.
